### ISSUE TITLE
Switching HDR on Windows 24H2 Build 26100 when "Automatically manage color for apps" is enabled in SDR mode

### ISSUE THREAD

**Issue by 1aTa** [res2k/HDRTray#13] opened 2024-07-17 10:48 UTC
Windows 24H2 Build 26100 has a new option which seems to be confusing all HDR mode switching utilities and media players, including HDRTray.

The new option "Automatically manage color for apps" under "System > Display > Color Management" increases the color range of Windows SDR to HDR levels to remove things like color banding. It works great and is very noticeable throughout the UI but a side effect is all apps think they are already in HDR mode, when they're actually not. With this option selected the only way I've found to switch the real Windows HDR mode on and off is with the toggle in Windows settings.

More info here: https://support.microsoft.com/en-us/windows/auto-color-management-in-windows-11-64a4de7f-9c93-43ec-bdf1-3b12ffa0870b

I wondered if you could look into this and potentially provide a solution for HDRTray?

**Comment by res2k** [comment] 2024-07-17 10:58
Thanks for the heads-up.
I'll see if I can find some developer docs on that new feature, this would hopefully shed some light on options here.
But since 24H2 appears to be an "Insider" build, which I'm not using, it may take a while until I can reproduce this issue myself.

That said, I suppose as an "Insider" build, the behavior wrt "old" applications may still change. So if you notice any change, please drop a comment here.

**Comment by 1aTa** [comment] 2024-07-17 11:10
It's already released in the Retail channel on arm64 (for Copilot+ PCs) and in the Release Preview channel on amd64 (Retail channel release imminent).

**Comment by res2k** [comment] 2024-07-18 14:55
Luckily, I remembered I have another device I could use to get the Release Preview 😅

I did some experimenting.
It seems Auto Color Management on SDR displays pretends HDR is enabled; "disabling" HDR will do something, as it'll disable Auto Color Management.
On HDR displays, it seems Auto Color Management will force HDR onto the display. This is what HDRTray will report.
Although, the Windows "Use HDR" toggle can still be switched, and it does _something_, if not disabling display HDR mode, perhaps it changes some composition/color mapping mode.

I guess the expectation is that using HDRTray is equivalent to the Windows "Use HDR" toggle.
The latest Windows SDK for 24H2 seems to provide some additional functionality related to automatic color management, perhaps I can figure out if that can be used to mimic the Windows behavior.

**Comment by 1aTa** [comment] 2024-07-18 15:07
Yeah ACM is still SDR, it just uses the same technology as Windows HDR for global color management. Turning ACM on in SDR mode switches my display to use the RGB_FULL_G2084_NONE_P2020 color space which removes a lot of banding throughout the UI.

Interesting find on the 24H2 SDK. Hopefully there's something in there which enables you to switch to the proper HDR mode. All media players and utilities with auto/manual HDR switching that I've tried currently have this same issue.

**Comment by res2k** [comment] 2024-07-21 12:07
@1aTa, you can find a build with improved Win 11 24H2 behavior here: https://github.com/res2k/HDRTray/actions/runs/10028092599
It seems to work as intended to the extent I tested it. Please give it a try and let me know how it works for you!

**Comment by 1aTa** [comment] 2024-07-21 12:44
It works absolutely perfectly, thank you so much!

This is the first app that I know of which resolves the issue and I've raised bug reports on quite a few. How did you fix it?

On a side note, I know someone else mentioned about providing quick access to the 'HDR content brightness slider' and you said it was out of scope of HDRTray. It would be awesome if you would consider adding one as I have to adjust that slider on a regular basis.

Huge props for the HDR switching fix though.

**Comment by res2k** [comment] 2024-07-21 16:46
> This is the first app that I know of which resolves the issue and I've raised bug reports on quite a few. How did you fix it?

The short of it: A combination of 1. noticing that that there's a new Windows SDK for 24H2, 2. realizing there are relevant new things, 3. the ability to install a Release Preview on a secondary machine, and 4. enough hardware to test out combinations with HDR, ACM enabled & disabled on both SDR and HDR displays.
With that it was relatively easy to figure out that, with ACM enabled, pretty much the new things have to be used to get and change the "real" HDR status.

> On a side note, I know someone else mentioned about providing quick access to the 'HDR content brightness slider' and you said it was out of scope of HDRTray. It would be awesome if you would consider adding one as I have to adjust that slider on a regular basis. Mouse wheel when hovered over the tray icon to adjust up and down would be great UX.

That UX suggestion sounds nice, please add it to the relevant issue (#4).
As I said, I might add brightness control when it gets more relevant to me.
There's some change it may - having experienced ACM a bit, it appears interesting to me; if I end up using it on my "daily driver" machine (after it went to 24H2), it may be a motivation to do this. (But I don't want to promise anything.)

**Comment by res2k** [comment] 2024-07-21 17:00
Closing, posted new release.

**Closed by res2k** 2024-07-21 17:00 UTC
